apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app-prod
  labels:
    app: minha-app
    environment: prod
spec:
  replicas: 3 # Mais réplicas para produção
  selector:
    matchLabels:
      app: minha-app
      environment: prod
  template:
    metadata:
      labels:
        app: minha-app
        environment: prod
    spec:
      containers:
      - name: minha-app
        image: SUA_CONTA_AWS.dkr.ecr.SUA_REGIAO.amazonaws.com/minha-app:latest # Esta tag será atualizada pelo Jenkins
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: minha-app-prod-service
spec:
  selector:
    app: minha-app
    environment: prod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
