apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-app-homolog
  labels:
    app: minha-app
    environment: homolog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minha-app
      environment: homolog
  template:
    metadata:
      labels:
        app: minha-app
        environment: homolog
    spec:
      containers:
      - name: minha-app
        image: SUA_CONTA_AWS.dkr.ecr.SUA_REGIAO.amazonaws.com/minha-app:latest # Esta tag será atualizada pelo Jenkins
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: minha-app-homolog-service
spec:
  selector:
    app: minha-app
    environment: homolog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
